### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by Mr6060** [Samplasion/plum-bot#5]
There is an annoying problem with the permission method:
Basically when the bot is in a server as well as his owner, the latter can do whatever they want only because he's the bot owner, even tho he has no permissions whatsoever to use some commands, this can lead to problems within the community.

**Comment by Samplasion** [comment]
The owner needs the higher permission to ensure that the bot works even with bugs/misconfigurations. Given I am the owner, I act in the best interest of the bot and its users.
